/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODE;

import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author usman
 */
public class LEVEL6 extends javax.swing.JFrame {

    /**
     * Creates new form LEVEL4
     */
     int cc=40;
       boolean suspended = true;
         int just=0;
    public LEVEL6() {
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);
         setSize(940,570);
         timeee2();
    }
    public void suspended()
    {
        suspended=false;
    }
    
    public void timeee2()
    {
        
        
      Thread clock;
             clock = new Thread()
             {
                 @Override
                 public void run()
                 {
                     
                     while(suspended)
                     {
                         
                         cc--;
                         String str = Integer.toString(cc);
                         
                         TIME2.setText(str);
                         if(cc==0)
                         {
                          JOptionPane.showMessageDialog(null, "Time Up");
                     
                          HHgG();
                         }
                         if(just==1)
                         {
                             suspended=false;
                         }
//  System.out.println("Ok");
                         try
                         {
                             
                             sleep(1000);
                             
                             
                             
                         }
                         catch(Exception e)
                             
                         {
                             
                         }
                     }
                    
                 }
             };
       clock.start();   
    }
    
    void HHgG()
    {
        MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
    }
    

    
    int scoree4;
    int hh;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mouthhh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        flower = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flow2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        appleeee = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rosee = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        palasLabel = new javax.swing.JLabel();
        sharabBotelLabel = new javax.swing.JLabel();
        sheshaLable = new javax.swing.JLabel();
        sweterLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SCORE4 = new javax.swing.JLabel();
        TIME2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnHint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        mouthhh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/7.JPG"))); // NOI18N
        mouthhh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouthhhMouseClicked(evt);
            }
        });
        getContentPane().add(mouthhh);
        mouthhh.setBounds(460, 60, 50, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Score:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 40);

        flower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/6.JPG"))); // NOI18N
        flower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flowerMouseClicked(evt);
            }
        });
        getContentPane().add(flower);
        flower.setBounds(890, 420, 90, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Find These Objects:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 10, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/df.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 20, 32, 32);

        flow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/9.JPG"))); // NOI18N
        flow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flow2MouseClicked(evt);
            }
        });
        getContentPane().add(flow2);
        flow2.setBounds(190, 240, 36, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/7.JPG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 20, 40, 35);

        number2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/5.JPG"))); // NOI18N
        number2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number2MouseClicked(evt);
            }
        });
        getContentPane().add(number2);
        number2.setBounds(340, 180, 90, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/6.JPG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 10, 42, 50);

        appleeee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/8.JPG"))); // NOI18N
        appleeee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appleeeeMouseClicked(evt);
            }
        });
        getContentPane().add(appleeee);
        appleeee.setBounds(390, 220, 130, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/9.JPG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 20, 36, 40);

        rosee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/df.png"))); // NOI18N
        rosee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseeMouseClicked(evt);
            }
        });
        getContentPane().add(rosee);
        rosee.setBounds(900, 310, 32, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/5.JPG"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(650, 10, 50, 50);

        palasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/38.JPG"))); // NOI18N
        palasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palasLabelMouseClicked(evt);
            }
        });
        getContentPane().add(palasLabel);
        palasLabel.setBounds(310, 390, 60, 90);

        sharabBotelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/39.JPG"))); // NOI18N
        sharabBotelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sharabBotelLabelMouseClicked(evt);
            }
        });
        getContentPane().add(sharabBotelLabel);
        sharabBotelLabel.setBounds(520, 450, 60, 32);

        sheshaLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/40.JPG"))); // NOI18N
        sheshaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sheshaLableMouseClicked(evt);
            }
        });
        getContentPane().add(sheshaLable);
        sheshaLable.setBounds(650, 260, 30, 45);

        sweterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/41.JPG"))); // NOI18N
        sweterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sweterLabelMouseClicked(evt);
            }
        });
        getContentPane().add(sweterLabel);
        sweterLabel.setBounds(590, 240, 50, 88);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/hidden-objects-3-in-1-crime-scene-pack-13082.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 69, 940, 470);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/8.JPG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(550, 20, 100, 40);

        SCORE4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SCORE4.setToolTipText("");
        getContentPane().add(SCORE4);
        SCORE4.setBounds(110, 20, 80, 30);

        TIME2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TIME2.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(TIME2);
        TIME2.setBounds(240, 50, 88, 20);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 50, 80, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/38.JPG"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(740, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/39.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(790, 20, 67, 32);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/40.JPG"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 10, 23, 45);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/41.JPG"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(860, -6, 50, 70);

        btnHint.setBackground(new java.awt.Color(51, 102, 0));
        btnHint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHint.setForeground(new java.awt.Color(255, 255, 255));
        btnHint.setText("Hint");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        getContentPane().add(btnHint);
        btnHint.setBounds(220, 40, 61, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouthhhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouthhhMouseClicked
        // TODO add your handling code here:
        
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     mouthhh.setVisible(false);
     jLabel4.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_mouthhhMouseClicked

    private void number2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseClicked
        // TODO add your handling code here:
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     number2.setVisible(false);
     jLabel9.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_number2MouseClicked

    private void flow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flow2MouseClicked
        // TODO add your handling code here:
        scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     flow2.setVisible(false);
     jLabel8.setVisible(false);
     
        hh++;
        checkGameee4();
    }//GEN-LAST:event_flow2MouseClicked

    private void flowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerMouseClicked
        // TODO add your handling code here:
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     flower.setVisible(false);
     jLabel6.setVisible(false);
        hh++;
        checkGameee4();
        
    }//GEN-LAST:event_flowerMouseClicked

    private void roseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseeMouseClicked
        // TODO add your handling code here:
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    rosee.setVisible(false);
    jLabel3.setVisible(false);
        hh++;
        checkGameee4();
        
    }//GEN-LAST:event_roseeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
         scoree4=scoree4-10;
        String str = Integer.toString(scoree4);
       
        SCORE4.setText(str);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void appleeeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleeeeMouseClicked
        // TODO add your handling code here:
        scoree4=scoree4+10;
        String str = Integer.toString(scoree4);

        SCORE4.setText(str);
        appleeee.setVisible(false);
        jLabel10.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_appleeeeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewGame n=new NewGame();
        n.gameSvaing("6");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void palasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palasLabelMouseClicked
        
                scoree4=scoree4+10;
        String str = Integer.toString(scoree4);

        SCORE4.setText(str);
        palasLabel.setVisible(false);
        jLabel11.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_palasLabelMouseClicked

    private void sharabBotelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharabBotelLabelMouseClicked
       
               scoree4=scoree4+10;
        String str = Integer.toString(scoree4);

        SCORE4.setText(str);
        sharabBotelLabel.setVisible(false);
        jLabel2.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_sharabBotelLabelMouseClicked

    private void sheshaLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sheshaLableMouseClicked
        
                scoree4=scoree4+10;
        String str = Integer.toString(scoree4);

        SCORE4.setText(str);
        sheshaLable.setVisible(false);
        jLabel12.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_sheshaLableMouseClicked

    private void sweterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sweterLabelMouseClicked
       
               scoree4=scoree4+10;
        String str = Integer.toString(scoree4);

        SCORE4.setText(str);
        sweterLabel.setVisible(false);
        jLabel14.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_sweterLabelMouseClicked

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null,"See Light Images.....");
    }//GEN-LAST:event_btnHintActionPerformed

    public void checkGameee4()
    {
        int res=1;
        if(hh==10)
        {
            if( scoree4>=60)
           {
             res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
             just=1;
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Your Scoore is to low");
           }
            //int res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        //just=1;
        if (res==JOptionPane.YES_OPTION)
        {
      //JOptionPane.showMessageDialog(null,"oK");
      LEVEL7 l7=new LEVEL7();
      l7.setVisible(true);
      this.setVisible(false);
      this.dispose();
          
          
            
            
            
          
        }
        else
        {
            
            MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEVEL6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SCORE4;
    private javax.swing.JLabel TIME2;
    private javax.swing.JLabel appleeee;
    private javax.swing.JButton btnHint;
    private javax.swing.JLabel flow2;
    private javax.swing.JLabel flower;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mouthhh;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel palasLabel;
    private javax.swing.JLabel rosee;
    private javax.swing.JLabel sharabBotelLabel;
    private javax.swing.JLabel sheshaLable;
    private javax.swing.JLabel sweterLabel;
    // End of variables declaration//GEN-END:variables
}
