/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODE;

import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author usman
 */
public class LEVEL5 extends javax.swing.JFrame {

    /**
     * Creates new form LEVEL2
     */
    
    int scor=0;//for score
    int obj=0;
    int cc=55;
    boolean suspended = true;
     int just=0;
    public LEVEL5() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
         setSize(780,600);
         timer.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alaram = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calculator = new javax.swing.JLabel();
        icecreame = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bottle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bottle1 = new javax.swing.JLabel();
        label33 = new javax.swing.JLabel();
        wood34Label = new javax.swing.JLabel();
        beltHookLabel = new javax.swing.JLabel();
        pipeLabel = new javax.swing.JLabel();
        lohaLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        scoree = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnHint2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        alaram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/dfsdfdf.png"))); // NOI18N
        alaram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alaramMouseClicked(evt);
            }
        });
        getContentPane().add(alaram);
        alaram.setBounds(500, 410, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/dfsdfdf.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 0, 110, 60);

        calculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/1.JPG"))); // NOI18N
        calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatorMouseClicked(evt);
            }
        });
        getContentPane().add(calculator);
        calculator.setBounds(80, 290, 40, 96);

        icecreame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/untitled.JPG"))); // NOI18N
        icecreame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icecreameMouseClicked(evt);
            }
        });
        getContentPane().add(icecreame);
        icecreame.setBounds(170, 320, 40, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/2.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 0, 60, 60);

        bottle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/2.JPG"))); // NOI18N
        bottle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottleMouseClicked(evt);
            }
        });
        getContentPane().add(bottle);
        bottle.setBounds(50, 130, 72, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/untitled.JPG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 10, 32, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/1.JPG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 0, 30, 50);

        bottle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/3.JPG"))); // NOI18N
        bottle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottle1MouseClicked(evt);
            }
        });
        getContentPane().add(bottle1);
        bottle1.setBounds(230, 230, 30, 230);

        label33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/33.JPG"))); // NOI18N
        label33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label33MouseClicked(evt);
            }
        });
        getContentPane().add(label33);
        label33.setBounds(190, 120, 20, 70);

        wood34Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/34.JPG"))); // NOI18N
        wood34Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wood34LabelMouseClicked(evt);
            }
        });
        getContentPane().add(wood34Label);
        wood34Label.setBounds(570, 130, 70, 60);

        beltHookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/35.JPG"))); // NOI18N
        beltHookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beltHookLabelMouseClicked(evt);
            }
        });
        getContentPane().add(beltHookLabel);
        beltHookLabel.setBounds(10, 420, 33, 130);

        pipeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/36.JPG"))); // NOI18N
        pipeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pipeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(pipeLabel);
        pipeLabel.setBounds(240, 110, 80, 60);

        lohaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/37.JPG"))); // NOI18N
        lohaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lohaLabelMouseClicked(evt);
            }
        });
        getContentPane().add(lohaLabel);
        lohaLabel.setBounds(0, 120, 170, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/wpid-photo-feb-6-2013-1252-am.jpg"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 120, 750, 480);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Score:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 10, 0, 40);
        getContentPane().add(timer);
        timer.setBounds(100, 40, 60, 20);

        scoree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(scoree);
        scoree.setBounds(110, 10, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/1.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 290, 70, 29);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 40, 70, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/33.JPG"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(578, 10, 20, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/34.JPG"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 10, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/35.JPG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 0, 40, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/3.JPG"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(700, 0, 20, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/36.JPG"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(720, 10, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/37.JPG"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(170, 10, 139, 30);

        btnHint2.setBackground(new java.awt.Color(51, 102, 0));
        btnHint2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHint2.setForeground(new java.awt.Color(255, 255, 255));
        btnHint2.setText("Hint");
        btnHint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHint2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHint2);
        btnHint2.setBounds(290, 80, 61, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void suspended()
    {
        suspended=false;
    }
public void timeee2()
    {
        
        
      Thread clock = null;
             clock = new Thread()
             {
                 @Override
                 public void run()
                 {
                     
                     while(suspended)
                     {
                         
                         cc--;
                         String str = Integer.toString(cc);
                         
                         timer.setText(str);
                         if(cc==0)
                         {
                          JOptionPane.showMessageDialog(null, "Time Up");
                          
                          HHgG();
                         }
                         if(just==1)
                         {
                             suspended();
                         }
                         
//  System.out.println("Ok");
                         try
                         {
                             
                             sleep(1000);
                             
                             
                             
                         }
                         catch(Exception e)
                             
                         {
                             
                         }
                     }
                    
                 }
             };
       clock.start();   
       
    }
    
    void HHgG()
    {
        MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
    }
    
    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
        
        
         scor=scor-10;
        String str = Integer.toString(scor);
       
        scoree.setText(str);
    }//GEN-LAST:event_backgroundMouseClicked

    private void alaramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alaramMouseClicked
        // TODO add your handling code here:
          scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
        alaram.setVisible(false);
        jLabel2.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_alaramMouseClicked

    private void calculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
       calculator.setVisible(false);
       jLabel4.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_calculatorMouseClicked

    private void icecreameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icecreameMouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
       icecreame.setVisible(false);
       jLabel6.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_icecreameMouseClicked

    private void bottleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottleMouseClicked
        // TODO add your handling code here:
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      bottle.setVisible(false);
      jLabel3.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_bottleMouseClicked

    private void bottle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottle1MouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      bottle1.setVisible(false);
      jLabel12.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_bottle1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       NewGame n=new NewGame();
        n.gameSvaing("5");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void label33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label33MouseClicked

        scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      label33.setVisible(false);
      jLabel9.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_label33MouseClicked

    private void wood34LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wood34LabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      wood34Label.setVisible(false);
      jLabel11.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_wood34LabelMouseClicked

    private void beltHookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beltHookLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      beltHookLabel.setVisible(false);
      jLabel10.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_beltHookLabelMouseClicked

    private void pipeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pipeLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      pipeLabel.setVisible(false);
      jLabel14.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_pipeLabelMouseClicked

    private void lohaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lohaLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      lohaLabel.setVisible(false);
      jLabel15.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_lohaLabelMouseClicked

    private void btnHint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHint2ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null,"See Light Images.....");
    }//GEN-LAST:event_btnHint2ActionPerformed

    public void checkGamee()
    {
        
         if(obj==10)
        {
            int res=1;
            if( scor>=50)
           {
             res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
             just=1;
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Your Scoore is to low");
           }
           // int res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
        if (res==JOptionPane.YES_OPTION)
        {
        //JOptionPane.showMessageDialog(null,"oK");
          
            
           LEVEL6 l6=new LEVEL6();
           l6.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
        else
        {
            
            MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEVEL5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alaram;
    private javax.swing.JLabel background;
    private javax.swing.JLabel beltHookLabel;
    private javax.swing.JLabel bottle;
    private javax.swing.JLabel bottle1;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnHint1;
    private javax.swing.JButton btnHint2;
    private javax.swing.JLabel calculator;
    private javax.swing.JLabel icecreame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label33;
    private javax.swing.JLabel lohaLabel;
    private javax.swing.JLabel pipeLabel;
    private javax.swing.JLabel scoree;
    private javax.swing.JLabel timer;
    private javax.swing.JLabel wood34Label;
    // End of variables declaration//GEN-END:variables
}
