/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODE;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usman
 */
public class LEVEL2 extends javax.swing.JFrame {

    /**
     * Creates new form LEVEL2
     */
    
    int scor=0;//for score
    int obj=0;
    public LEVEL2() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
         setSize(680,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alaram = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        icecreame = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calculator = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bottle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bottle1 = new javax.swing.JLabel();
        sBotelLAbel = new javax.swing.JLabel();
        newIceCreamLabel = new javax.swing.JLabel();
        sheshaLabel = new javax.swing.JLabel();
        lockLabel = new javax.swing.JLabel();
        cdLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scoree = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        alaram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/fr.png"))); // NOI18N
        alaram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alaramMouseClicked(evt);
            }
        });
        getContentPane().add(alaram);
        alaram.setBounds(480, 400, 64, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/oppp.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 10, 50, 50);

        icecreame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/hn.png"))); // NOI18N
        icecreame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icecreameMouseClicked(evt);
            }
        });
        getContentPane().add(icecreame);
        icecreame.setBounds(180, 270, 60, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Find These Objects:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 20, 180, 30);

        calculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/defff.png"))); // NOI18N
        calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatorMouseClicked(evt);
            }
        });
        getContentPane().add(calculator);
        calculator.setBounds(50, 410, 70, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/bo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 10, 40, 50);

        bottle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/booo.png"))); // NOI18N
        bottle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottleMouseClicked(evt);
            }
        });
        getContentPane().add(bottle);
        bottle.setBounds(80, 110, 72, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/ice2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 10, 40, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/de.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 10, 48, 50);

        bottle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/booo.png"))); // NOI18N
        bottle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottle1MouseClicked(evt);
            }
        });
        getContentPane().add(bottle1);
        bottle1.setBounds(580, 130, 50, 80);

        sBotelLAbel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/63.JPG"))); // NOI18N
        sBotelLAbel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sBotelLAbelMouseClicked(evt);
            }
        });
        getContentPane().add(sBotelLAbel);
        sBotelLAbel.setBounds(200, 470, 31, 109);

        newIceCreamLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/64.JPG"))); // NOI18N
        newIceCreamLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newIceCreamLabelMouseClicked(evt);
            }
        });
        getContentPane().add(newIceCreamLabel);
        newIceCreamLabel.setBounds(400, 470, 36, 73);

        sheshaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/65.JPG"))); // NOI18N
        sheshaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sheshaLabelMouseClicked(evt);
            }
        });
        getContentPane().add(sheshaLabel);
        sheshaLabel.setBounds(615, 400, 50, 57);

        lockLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/66.JPG"))); // NOI18N
        lockLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockLabelMouseClicked(evt);
            }
        });
        getContentPane().add(lockLabel);
        lockLabel.setBounds(610, 310, 40, 52);

        cdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/67.JPG"))); // NOI18N
        cdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdLabelMouseClicked(evt);
            }
        });
        getContentPane().add(cdLabel);
        cdLabel.setBounds(30, 370, 43, 46);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/2.png"))); // NOI18N
        background.setText("jLabel1");
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 80, 760, 520);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Score:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 10, 0, 40);

        scoree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(scoree);
        scoree.setBounds(110, 10, 70, 50);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 50, 75, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/63.JPG"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(550, 10, 30, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/64.JPG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 10, 40, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/65.JPG"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 14, 45, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/66.JPG"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 14, 33, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/67.JPG"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(720, 20, 40, 40);

        btnHint.setBackground(new java.awt.Color(51, 102, 0));
        btnHint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHint.setForeground(new java.awt.Color(255, 255, 255));
        btnHint.setText("Hint");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        getContentPane().add(btnHint);
        btnHint.setBounds(210, 50, 61, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
        
        
         scor=scor-10;
        String str = Integer.toString(scor);
       
        scoree.setText(str);
    }//GEN-LAST:event_backgroundMouseClicked

    private void alaramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alaramMouseClicked
        // TODO add your handling code here:
          scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
        alaram.setVisible(false);
        jLabel2.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_alaramMouseClicked

    private void calculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
       calculator.setVisible(false);
       jLabel4.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_calculatorMouseClicked

    private void icecreameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icecreameMouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
       icecreame.setVisible(false);
       jLabel6.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_icecreameMouseClicked

    private void bottleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottleMouseClicked
        // TODO add your handling code here:
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      bottle.setVisible(false);
      jLabel3.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_bottleMouseClicked

    private void bottle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottle1MouseClicked
        // TODO add your handling code here:
        
         scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      bottle1.setVisible(false);
        obj++;
        checkGamee();
        
    }//GEN-LAST:event_bottle1MouseClicked

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewGame n=new NewGame();
        n.gameSvaing("2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sBotelLAbelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sBotelLAbelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      sBotelLAbel.setVisible(false);
      jLabel9.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_sBotelLAbelMouseClicked

    private void newIceCreamLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newIceCreamLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      newIceCreamLabel.setVisible(false);
      jLabel10.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_newIceCreamLabelMouseClicked

    private void sheshaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sheshaLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      sheshaLabel.setVisible(false);
      jLabel11.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_sheshaLabelMouseClicked

    private void lockLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      lockLabel.setVisible(false);
      jLabel12.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_lockLabelMouseClicked

    private void cdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdLabelMouseClicked
        
                scor=scor+10;
       String str = Integer.toString(scor);
       
       scoree.setText(str);
      cdLabel.setVisible(false);
      jLabel13.setVisible(false);
        obj++;
        checkGamee();
    }//GEN-LAST:event_cdLabelMouseClicked

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null,"See Accesiories Images.....");
    }//GEN-LAST:event_btnHintActionPerformed

    public void checkGamee()
    {
        int res=1;
        
         if(obj==10)
        {
            if( scor>30)
           {
             res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Your Scoore is to low");
           }
            //int res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
        if (res==JOptionPane.YES_OPTION)
        {
        //JOptionPane.showMessageDialog(null,"oK");
          
            
           LEVEL3 l3=new LEVEL3();
           l3.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
        else
        {
            
            MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEVEL2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEVEL2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alaram;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottle;
    private javax.swing.JLabel bottle1;
    private javax.swing.JButton btnHint;
    private javax.swing.JLabel calculator;
    private javax.swing.JLabel cdLabel;
    private javax.swing.JLabel icecreame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lockLabel;
    private javax.swing.JLabel newIceCreamLabel;
    private javax.swing.JLabel sBotelLAbel;
    private javax.swing.JLabel scoree;
    private javax.swing.JLabel sheshaLabel;
    // End of variables declaration//GEN-END:variables
}
