/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODE;

import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author usman
 */
public class LEVEL4 extends javax.swing.JFrame {

    /**
     * Creates new form LEVEL4
     */
     int cc=60;
     boolean suspended = true;
     int just=0;
    public LEVEL4() {
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);
         setSize(900,580);
         timeee2();
         
    }
    public void suspended()
    {
        suspended=false;
    }
    
    
    public void timeee2()
    {
        
        
      Thread clock = null;
             clock = new Thread()
             {
                 @Override
                 public void run()
                 {
                     
                     while(suspended)
                     {
                         
                         cc--;
                         String str = Integer.toString(cc);
                         
                         TIME2.setText(str);
                         if(cc==0)
                         {
                          JOptionPane.showMessageDialog(null, "Time Up");
                          
                          HHgG();
                         }
                         if(just==1)
                         {
                             suspended();
                         }
                         
//  System.out.println("Ok");
                         try
                         {
                             
                             sleep(1000);
                             
                             
                             
                         }
                         catch(Exception e)
                             
                         {
                             
                         }
                     }
                    
                 }
             };
       clock.start();   
       
    }
    
    void HHgG()
    {
        MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
    }
    

    
    int scoree4;
    int hh;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mouthhh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        flower = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flow2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        appleeee = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rosee = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        shoeLabel = new javax.swing.JLabel();
        pageLabel = new javax.swing.JLabel();
        bagLabel = new javax.swing.JLabel();
        jugLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SCORE4 = new javax.swing.JLabel();
        TIME2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnHint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        mouthhh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/222.png"))); // NOI18N
        mouthhh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouthhhMouseClicked(evt);
            }
        });
        getContentPane().add(mouthhh);
        mouthhh.setBounds(250, 300, 50, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Score:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 40);

        flower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/flowww.png"))); // NOI18N
        flower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flowerMouseClicked(evt);
            }
        });
        getContentPane().add(flower);
        flower.setBounds(610, 250, 86, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Find These Objects:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 10, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/df.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 10, 32, 32);

        flow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/G12-Flower-icon.png"))); // NOI18N
        flow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flow2MouseClicked(evt);
            }
        });
        getContentPane().add(flow2);
        flow2.setBounds(850, 380, 86, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/der.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 10, 32, 32);

        number2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/number-2-icon.png"))); // NOI18N
        number2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number2MouseClicked(evt);
            }
        });
        getContentPane().add(number2);
        number2.setBounds(740, 120, 32, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/sd.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 10, 32, 32);

        appleeee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/appllll.png"))); // NOI18N
        appleeee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appleeeeMouseClicked(evt);
            }
        });
        getContentPane().add(appleeee);
        appleeee.setBounds(400, 390, 32, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/G12-Flower-icon.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 10, 32, 32);

        rosee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/df.png"))); // NOI18N
        rosee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseeMouseClicked(evt);
            }
        });
        getContentPane().add(rosee);
        rosee.setBounds(850, 380, 32, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/number-2-icon.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 10, 32, 32);

        shoeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/58.JPG"))); // NOI18N
        shoeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(shoeLabel);
        shoeLabel.setBounds(10, 180, 80, 70);

        pageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/59.JPG"))); // NOI18N
        pageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pageLabelMouseClicked(evt);
            }
        });
        getContentPane().add(pageLabel);
        pageLabel.setBounds(210, 90, 110, 90);

        bagLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/60.JPG"))); // NOI18N
        bagLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bagLabelMouseClicked(evt);
            }
        });
        getContentPane().add(bagLabel);
        bagLabel.setBounds(560, 310, 55, 49);

        jugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/61.JPG"))); // NOI18N
        jugLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugLabelMouseClicked(evt);
            }
        });
        getContentPane().add(jugLabel);
        jugLabel.setBounds(450, 190, 19, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/lo.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 80, 890, 459);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/appllll.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(640, 10, 32, 32);

        SCORE4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SCORE4.setToolTipText("");
        getContentPane().add(SCORE4);
        SCORE4.setBounds(110, 20, 80, 30);

        TIME2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TIME2.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(TIME2);
        TIME2.setBounds(290, 50, 88, 20);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 60, 80, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/58.JPG"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(720, 10, 80, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/59.JPG"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(810, 10, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/60.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(425, 10, 50, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODE/61.JPG"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 10, 19, 50);

        btnHint.setBackground(new java.awt.Color(51, 102, 0));
        btnHint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHint.setForeground(new java.awt.Color(255, 255, 255));
        btnHint.setText("Hint");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        getContentPane().add(btnHint);
        btnHint.setBounds(210, 50, 61, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouthhhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouthhhMouseClicked
        // TODO add your handling code here:
        
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     mouthhh.setVisible(false);
     jLabel4.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_mouthhhMouseClicked

    private void number2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseClicked
        // TODO add your handling code here:
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     number2.setVisible(false);
     jLabel9.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_number2MouseClicked

    private void appleeeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleeeeMouseClicked
        // TODO add your handling code here:
        scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     appleeee.setVisible(false);
     jLabel10.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_appleeeeMouseClicked

    private void flow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flow2MouseClicked
        // TODO add your handling code here:
        scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     flow2.setVisible(false);
     jLabel8.setVisible(false);
     
        hh++;
        checkGameee4();
    }//GEN-LAST:event_flow2MouseClicked

    private void flowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerMouseClicked
        // TODO add your handling code here:
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
     flower.setVisible(false);
     jLabel6.setVisible(false);
        hh++;
        checkGameee4();
        
    }//GEN-LAST:event_flowerMouseClicked

    private void roseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseeMouseClicked
        // TODO add your handling code here:
        
         scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    rosee.setVisible(false);
    jLabel3.setVisible(false);
        hh++;
        checkGameee4();
        
    }//GEN-LAST:event_roseeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
         scoree4=scoree4-10;
        String str = Integer.toString(scoree4);
       
        SCORE4.setText(str);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewGame n=new NewGame();
        n.gameSvaing("4");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shoeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoeLabelMouseClicked
        
                scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    shoeLabel.setVisible(false);
    jLabel11.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_shoeLabelMouseClicked

    private void pageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pageLabelMouseClicked
        
                scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    pageLabel.setVisible(false);
    jLabel12.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_pageLabelMouseClicked

    private void bagLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagLabelMouseClicked
        
                scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    bagLabel.setVisible(false);
    jLabel2.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_bagLabelMouseClicked

    private void jugLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugLabelMouseClicked
        
                scoree4=scoree4+10;
       String str = Integer.toString(scoree4);
       
       SCORE4.setText(str);
    jugLabel.setVisible(false);
    jLabel14.setVisible(false);
        hh++;
        checkGameee4();
    }//GEN-LAST:event_jugLabelMouseClicked

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"See Light Images.....");
    }//GEN-LAST:event_btnHintActionPerformed

    public void checkGameee4()
    {
        int res=1;
        if(hh==10)
        {
            if( scoree4>=50)
           {
             res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
             just=1;
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Your Scoore is to low");
           }
            //int res= JOptionPane.showConfirmDialog(null,"Congratulations you have found all the hidden objects." + "\n"+" Do you want to continue? ");
        
        if (res==JOptionPane.YES_OPTION)
        {
     // JOptionPane.showMessageDialog(null,"oK");
      //just=1;
      LEVEL5 l5=new LEVEL5();
      l5.setVisible(true);
      this.setVisible(false);
      this.dispose();
          
          
            
            
            
          
        }
        else
        {
            
            MainMenu m1=new MainMenu();
            m1.setVisible(true);
           this.setVisible(false);
           this.dispose();
        }
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEVEL4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEVEL4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SCORE4;
    private javax.swing.JLabel TIME2;
    private javax.swing.JLabel appleeee;
    private javax.swing.JLabel bagLabel;
    private javax.swing.JButton btnHint;
    private javax.swing.JLabel flow2;
    private javax.swing.JLabel flower;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jugLabel;
    private javax.swing.JLabel mouthhh;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JLabel rosee;
    private javax.swing.JLabel shoeLabel;
    // End of variables declaration//GEN-END:variables
}
